- name: Ensure Docker Repo GPG key
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/{{ ansible_distribution | lower }}
    components:
      - stable
    state: present
    architectures: "{{ hashi_arch[ansible_facts.architecture] }}"
    suites: "{{ ansible_facts[distribution] }}"
    signed_by: "{{ docker_repo_key_url }}"
    trusted: true
    enabled: true
    mode: "0644"

- name: Ensure docker packages
  ansible.builtin.package:
    name: "{{ docker_packages }}"
    state: present
    update_cache: true
