---
# handlers file for ansible-role-nomad
- name: Reload service
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart logrotate
  ansible.builtin.service:
    name: logrotate
    state: restarted
