---
name: Release
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: ansible lint
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Add Dev tools
        uses: jdx/mise-action@v5
        with:
          install: true
      - name: Add dev deps
        run: mise tasks run install_deps
      - name: Ansible Lint
        run: ansible-lint
        # env:
        #   ANSIBLE_ROLES_PATH: "${PWD}/../"
  packer_lint:
    name: Packer lint
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Add Dev tools
        uses: jdx/mise-action@v5
        with:
          install: true
      - name: Add dev deps
        run: mise tasks run install_deps
      - name: Init packer
        run: packer init .
        working-directory: .github/build

  release:
    name: Release
    needs:
      - lint
      - packer_lint
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "26"
      - name: add semantic release plugins
        run: |
          npm install -D '@semantic-release/changelog' \
                          '@semantic-release/git'

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
  build:
    name: Build
    needs:
      - release
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Add Dev tools
        uses: jdx/mise-action@v5
        with:
          install: true
      - name: Add dev deps
        run: mise tasks run install_deps
